name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run unit tests
      run: npm run test:unit
    - name: Display softuni username
      run: echo gretaptrv

  ui_test:
    runs-on: ubuntu-latest
    needs: build_and_unit_test
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Install Playwright
      run: npx playwright install
    - name: Run Application
      run: npm run start &
    - name: Run ui tests
      run: npm run test:ui

  deploy_to_render:
    runs-on: ubuntu-latest
    needs: ui_test
    steps:
      - name: Deploy
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_TOKEN }}
